[Proxy]
Singapore 01 = tuic, aws-sg-1.nesnode.com, 443, version=5, uuid=076f3feb-8f3c-4da4-88bc-6045300fcc5f, password=4ktTv/w3UlQ4z+3ovxacnQ==, sni=aws.amazon.com, alpn=h3, skip-cert-verify=true
Singapore 02 = tuic, aws-sg-2.nesnode.com, 443, version=5, uuid=076f3feb-8f3c-4da4-88bc-6045300fcc5f, password=4ktTv/w3UlQ4z+3ovxacnQ==, sni=aws.amazon.com, alpn=h3, skip-cert-verify=true
Singapore 03 = tuic, aws-sg-3.nesnode.com, 443, version=5, uuid=076f3feb-8f3c-4da4-88bc-6045300fcc5f, password=4ktTv/w3UlQ4z+3ovxacnQ==, sni=aws.amazon.com, alpn=h3, skip-cert-verify=true
Singapore 04 = tuic, aws-sg-6.nesnode.com, 443, version=5, uuid=076f3feb-8f3c-4da4-88bc-6045300fcc5f, password=4ktTv/w3UlQ4z+3ovxacnQ==, sni=aws.amazon.com, alpn=h3, skip-cert-verify=true
Singapore 05 = tuic, aws-sg-5.nesnode.com, 443, version=5, uuid=076f3feb-8f3c-4da4-88bc-6045300fcc5f, password=4ktTv/w3UlQ4z+3ovxacnQ==, sni=aws.amazon.com, alpn=h3, skip-cert-verify=true

[Proxy Group]
Proxy = url-test, Singapore 01, Singapore 02, Singapore 03, Singapore 04, Singapore 05

[Rule]
GEOIP, CN, DIRECT
FINAL, Proxy
