[Proxy]
Taiwan 01 = trojan, f3a9k5d8.gabuit.com, 48606, password = 7E25ED5B-DB74-4869-8A40-AB3261DC2428, sni = a1d8v4.maskmont.com, tfo = true, udp-relay = true
Taiwan 02 = trojan, f3a9k5d8.gabuit.com, 48607, password = 7E25ED5B-DB74-4869-8A40-AB3261DC2428, sni = a1d8v4.maskmont.com, tfo = true, udp-relay = true
Japan 01 = trojan, f3a9k5d8.gabuit.com, 48609, password = 7E25ED5B-DB74-4869-8A40-AB3261DC2428, sni = a1d8v4.maskmont.com, tfo = true, udp-relay = true
Japan 02 = trojan, f3a9k5d8.gabuit.com, 48610, password = 7E25ED5B-DB74-4869-8A40-AB3261DC2428, sni = a1d8v4.maskmont.com, tfo = true, udp-relay = true
Japan 03 = trojan, f3a9k5d8.gabuit.com, 48611, password = 7E25ED5B-DB74-4869-8A40-AB3261DC2428, sni = a1d8v4.maskmont.com, tfo = true, udp-relay = true
Singapore 01 = trojan, f3a9k5d8.gabuit.com, 48616, password = 7E25ED5B-DB74-4869-8A40-AB3261DC2428, sni = a1d8v4.maskmont.com, tfo = true, udp-relay = true
Singapore 02 = trojan, f3a9k5d8.gabuit.com, 48617, password = 7E25ED5B-DB74-4869-8A40-AB3261DC2428, sni = a1d8v4.maskmont.com, tfo = true, udp-relay = true

[Proxy Group]
Proxy = select, Taiwan 01, Taiwan 02, Japan 01, Japan 02, Japan 03, Singapore 01, Singapore 02

[Rule]
GEOIP, CN, DIRECT
FINAL, Proxy
