[Proxy]
Singapore 01 = https, aws-sg-1.nesnode.com, 443, username=076f3feb8f3c4da488bc6045300fcc5f, password=4ktTv/w3UlQ4z+3ovxacnQ==, sni=aws.amazon.com, skip-cert-verify=true, tfo=true
Singapore 02 = https, aws-sg-2.nesnode.com, 443, username=076f3feb8f3c4da488bc6045300fcc5f, password=4ktTv/w3UlQ4z+3ovxacnQ==, sni=aws.amazon.com, skip-cert-verify=true, tfo=true
Singapore 03 = https, aws-sg-3.nesnode.com, 443, username=076f3feb8f3c4da488bc6045300fcc5f, password=4ktTv/w3UlQ4z+3ovxacnQ==, sni=aws.amazon.com, skip-cert-verify=true, tfo=true
Singapore 04 = https, aws-sg-6.nesnode.com, 443, username=076f3feb8f3c4da488bc6045300fcc5f, password=4ktTv/w3UlQ4z+3ovxacnQ==, sni=aws.amazon.com, skip-cert-verify=true, tfo=true
Singapore 05 = https, aws-sg-5.nesnode.com, 443, username=076f3feb8f3c4da488bc6045300fcc5f, password=4ktTv/w3UlQ4z+3ovxacnQ==, sni=aws.amazon.com, skip-cert-verify=true, tfo=true
Hong Kong 01 = https, aws-hk-1.nesnode.com, 443, username=076f3feb8f3c4da488bc6045300fcc5f, password=4ktTv/w3UlQ4z+3ovxacnQ==, sni=aws.amazon.com, skip-cert-verify=true, tfo=true
Hong Kong 02 = https, aws-hk-2.nesnode.com, 443, username=076f3feb8f3c4da488bc6045300fcc5f, password=4ktTv/w3UlQ4z+3ovxacnQ==, sni=aws.amazon.com, skip-cert-verify=true, tfo=true
Hong Kong 03 = https, aws-hk-3.nesnode.com, 443, username=076f3feb8f3c4da488bc6045300fcc5f, password=4ktTv/w3UlQ4z+3ovxacnQ==, sni=aws.amazon.com, skip-cert-verify=true, tfo=true
Japan 01 = https, aws-jp-1.nesnode.com, 443, username=076f3feb8f3c4da488bc6045300fcc5f, password=4ktTv/w3UlQ4z+3ovxacnQ==, sni=aws.amazon.com, skip-cert-verify=true, tfo=true
Japan 02 = https, aws-jp-3.nesnode.com, 443, username=076f3feb8f3c4da488bc6045300fcc5f, password=4ktTv/w3UlQ4z+3ovxacnQ==, sni=aws.amazon.com, skip-cert-verify=true, tfo=true
Japan 03 = https, aws-jp-4.nesnode.com, 443, username=076f3feb8f3c4da488bc6045300fcc5f, password=4ktTv/w3UlQ4z+3ovxacnQ==, sni=aws.amazon.com, skip-cert-verify=true, tfo=true
Seoul 01 = https, aws-seoul-1.nesnode.com, 443, username=076f3feb8f3c4da488bc6045300fcc5f, password=4ktTv/w3UlQ4z+3ovxacnQ==, sni=aws.amazon.com, skip-cert-verify=true, tfo=true
Malaysia 01 = https, aws-my-1.nesnode.com, 443, username=076f3feb8f3c4da488bc6045300fcc5f, password=4ktTv/w3UlQ4z+3ovxacnQ==, sni=aws.amazon.com, skip-cert-verify=true, tfo=true
Malaysia 02 = https, aws-my-2.nesnode.com, 443, username=076f3feb8f3c4da488bc6045300fcc5f, password=4ktTv/w3UlQ4z+3ovxacnQ==, sni=aws.amazon.com, skip-cert-verify=true, tfo=true

[Proxy Group]
Proxy  = select, Singapore 01, Singapore 02, Singapore 03, Singapore 04, Singapore 05, Hong Kong 01, Hong Kong 02, Hong Kong 03, Japan 01, Japan 02, Japan 03, Seoul 01, Malaysia 01, Malaysia 02

[Rule]
GEOIP, CN, DIRECT
FINAL, Proxy
