[Proxy]
Singapore 01 = anytls, aws-sg-1.nesnode.com, 8443, password=4ktTv/w3UlQ4z+3ovxacnQ==, sni=aws.amazon.com, reality=true, reality-public-key=FV0-uJFNgABjrla9zjO2WdnYO4fmwugD5zcmc32nKk0, reality-short-id=0246802789abcdef, client-fingerprint=chrome
Singapore 02 = anytls, aws-sg-2.nesnode.com, 8443, password=4ktTv/w3UlQ4z+3ovxacnQ==, sni=aws.amazon.com, reality=true, reality-public-key=FV0-uJFNgABjrla9zjO2WdnYO4fmwugD5zcmc32nKk0, reality-short-id=0246802789abcdef, client-fingerprint=chrome
Singapore 03 = anytls, aws-sg-3.nesnode.com, 8443, password=4ktTv/w3UlQ4z+3ovxacnQ==, sni=aws.amazon.com, reality=true, reality-public-key=FV0-uJFNgABjrla9zjO2WdnYO4fmwugD5zcmc32nKk0, reality-short-id=0246802789abcdef, client-fingerprint=chrome
Singapore 04 = anytls, aws-sg-5.nesnode.com, 8443, password=4ktTv/w3UlQ4z+3ovxacnQ==, sni=aws.amazon.com, reality=true, reality-public-key=FV0-uJFNgABjrla9zjO2WdnYO4fmwugD5zcmc32nKk0, reality-short-id=0246802789abcdef, client-fingerprint=chrome
Singapore 05 = anytls, aws-sg-6.nesnode.com, 8443, password=4ktTv/w3UlQ4z+3ovxacnQ==, sni=aws.amazon.com, reality=true, reality-public-key=FV0-uJFNgABjrla9zjO2WdnYO4fmwugD5zcmc32nKk0, reality-short-id=0246802789abcdef, client-fingerprint=chrome

[Proxy Group]
Proxy = url-test, Singapore 01, Singapore 02, Singapore 03, Singapore 04, Singapore 05

[Rule]
GEOIP, CN, DIRECT
FINAL, Proxy
